Fix crash when --tags argument is used
The code was trying to call .decode on a str() instance. In Python 3,
this can only be done on bytes() instance.

Fixes the following backtrace when running `pinboard get --tag ...` or
`pinboard bookmark --tag ...`

    Traceback (most recent call last):
      File "/home/sam/.local/bin/pinboard", line 6, in <module>
        exec(compile(open(__file__).read(), __file__, 'exec'))
      File "/home/sam/src/pinboard.py/bin/pinboard", line 363, in <module>
        handler.run()
      File "/home/sam/src/pinboard.py/bin/pinboard", line 280, in run
        command_map[self.namespace.subparser]()
      File "/home/sam/src/pinboard.py/bin/pinboard", line 109, in _bookmarks_action
        self._call_api_and_catch_exceptions(self.pinboard.posts.all, **kwargs)
      File "/home/sam/src/pinboard.py/bin/pinboard", line 74, in _call_api_and_catch_exceptions
        response = fun(parse_response=False, *args, **kwargs)
      File "/home/sam/src/pinboard.py/pinboard/pinboard.py", line 167, in __call__
        params[field] = ' '.join(value)
      File "/home/sam/src/pinboard.py/pinboard/pinboard.py", line 166, in <lambda>
        value = map(lambda k: k.decode("utf8"), kwargs[field])
    AttributeError: 'str' object has no attribute 'decode'